services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - "${FORWARD_PORT:-8000}:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: queue
    container_name: queue
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

volumes:
  mysql:
